### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by mhaut** [avulanov/scalable-deeplearning#3]
Hi @avulanov @JeremyNixon,

I would like work in the python interface (I will try to create classifier, autoencoder and regressor). The problem is that Spark has several classes in several files. Do you want to keep the same directory structure? or prefer a different structure.

For the other hand, py4j has copyright? (https://github.com/apache/spark/tree/master/python/lib)

thanks!

**Comment by avulanov** [comment]
@mhaut Thanks for your interest in the project! We can replicate the way the python interface works in Spark. It has an implementation for MultilayerPerceptron.

**Comment by mhaut** [comment]
Thanks for yours great contributions! Sorry, but I don't have much times for create a complete feature. If you want, I can write a Python interface for autoencoder and regressor in order to spark integration.
